import Dashboard from "@/components/Dashboard";
import Login from "@/components/Login";
import Head from "next/head";
import { useState } from "react";
import jwt from "jsonwebtoken";

export default function Home() {
  const defaultValue = {
    username: "",
    password: "",
  };
  const [data, setData] = useState(defaultValue);
  const [message, setMessage] = useState("You are not logged in");
  const [secret, setSecret] = useState("Secret");

  const handleInputs = (event) => {
    const { name, value } = event.target;
    setData({ ...data, [name]: value });
  };
  const submitForm = async (e) => {
    e.preventDefault();
    const res = await fetch("/api/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((t) => t.json());

    const token = res.token;

    if (token) {
      const json = jwt.decode(token);
      console.log("JSON", json);
      setMessage(
        `Welcome ${json.username} and you are ${
          json.admin ? "an admin ! " : "not an admin"
        }`
      );
       
      const res = await fetch("/api/secret", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(token),
      }).then((t) => t.json());


      if(res.secretAdminCode){
        setSecret( res.secretAdminCode)
      }
      else{
        setSecret( "Notthing")
      }

    } else {
      setMessage("Something went wrong");
    }
  };

  return (
    <>
      <Head>
        <title>JWT Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{message}</h1>
      <h1>{secret}</h1>
      <form>
        <input
          name="username"
          type="text"
          value={data.username}
          onChange={handleInputs}
        ></input>
        <br></br>
        <input
          type="password"
          name="password"
          value={data.password}
          onChange={handleInputs}
        ></input>
        <br></br>
        <input
          type="submit"
          value="Login"
          onClick={(e) => {
            submitForm(e);
          }}
        ></input>
      </form>

      <Login />
      <Dashboard />
    </>
  );
}
